name: Playwright Allure Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
<<<<<<< HEAD
    - cron: '0 0 * * *' # This runs the job daily at midnight
=======
    - cron: '* * * * *'
>>>>>>> b3b090cde3ab2395547561ff835f369f95f96bfb

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Download Allure History Artifact
      if: always()
      uses: actions/download-artifact@v3
      with:
        name: allure-results-history
        path: allure-results/history

    - name: Run Playwright tests with retries
      run: npx playwright test --reporter=allure-playwright --retries=2

    - name: Save Allure History
      if: always()
      run: |
        echo "Saving Allure history..."
        mkdir -p allure-results-history
        cp -r allure-results/history allure-results-history

    - name: Upload Allure History Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-history
        path: allure-results-history

    - name: Generate Allure Report
      run: npx allure generate allure-results --output allure-report --clean

    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
